development:
  adapter: postgresql
  encoding: unicode
  database: api_react
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: api_react_test
  pool: 5
  username:
  password:
