development:
  adapter: postgresql
  encoding: unicode
  database: api_rails
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: api_rails_test
  pool: 5
  username:
  password:
